os:
  - linux
language: scala
scala:
   - 2.11.7
jdk:
  - oraclejdk8
sudo: false
sbt_args: -no-colors -J-Xss2m
script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls