os:
  - linux
language: scala
scala:
   - 2.11.7
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
before_install:
    - export COVERALLS_REPO_TOKEN=gc6Wo2u12Q9FgSDuZK82mG8FyFJMwzNTD
sbt_args: -no-colors -J-Xss2m
script:
    - sbt clean coverage test
      sbt coverageReport
      sbt coverageAggregate
after_success:
  - sbt coveralls